### ISSUE TITLE
Grading Issue Vibha

### ISSUE THREAD

**Issue by vibha-yganji** [jplip/frontTri2#10]

**Comment by varunm532** [comment]
Individual Review "Varun" grading "Vidha "

- [x] Individual should show that they were key contributor and example to team.  This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom. (0.7, had code and committed it to the project, but more commits through the week would be better. Also project is not in homepage)

Individuals Video, Issue(s), Commits(s)

- [ ] Video in CPT caption style , includes Web demo of key contribution to project, 1 minute ( 0.55, no video )
- [ ] Issue(s) that show plans/progress to team objectives (0.55 no issues that show plans/progress to team objectives)
- [x] Highlights of key commit(s) in Issues, summarizes code contributions (0.7 showed major commits and summarized code/project to me. But the project is not full functional
- [x] Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks (0.7, has commits through the 3 weeks, but they aren't that consistent. Most of the commits happened during the beginning and end of the 3 weeks
 
Overall: 0.64
 Freeform comment.  
The Project is partially working, but it could be improved especially in Sass/styling from what I saw. There was no video and no issues were shown.  The project has a good idea, but regularly committing is recommended. Also once finishing the project you should add it to the home page.
