### ISSUE TITLE
Final Crossover Review Ticket -Justin Liporada

### ISSUE THREAD

**Issue by jplip** [jplip/frontTri2#5]
Name | Team+Indi+Teacher | Runtime | Key Commit(s) | Videos |Analytics
-- | -- | -- | -- | -- | --
Justin L |  | 1. [Steganography](https://jplip.github.io/frontTri2/Steganography/), 2. [Binary Color](https://jplip.github.io/frontTri2/BinaryColor/) | 1. [Steganography](https://github.com/jplip/frontTri2/commit/14e18fac0dce4da3d04a476fc3d1ec1292e37239), 2. [Binary Color](https://github.com/jplip/frontTri2/commit/193a14de03a002d1494d83595e6b600b26953cd3)| [Steganography](https://www.veed.io/view/bfdc7578-8306-4028-b2e0-ba5f25efe8b2?panel=share), [Binary Color](https://www.veed.io/view/682e790c-f826-45df-9d9b-a067b576176b?panel=share)| [Commits](https://github.com/jplip/frontTri2/commits?author=jplip), [Profile](https://github.com/jplip)

[Frontend](https://github.com/jplip/frontTri2)
[Website](https://jplip.github.io/frontTri2/)
[Team Link](https://github.com/jplip/frontTri2/issues/4)

**Comment by TDWolff** [comment]
Individual Review: Torin Wolff grading: Justin Liporada

- [✓] The individual should show that they were key contributor and example to team.  This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom. 
- He contributed to the group with his key commits 0.9/1

Individuals Video, Issue(s), Commits(s)

- [✓] Video in CPT caption style, includes Web demo of key contribution to project, 1 minute: Video consisted of some captions, demonstrated his work 0.9/1
- [] Issue(s) that show plans/progress to team objectives: Didn't have a lot of issues but did have a big commit 0.7/1
- [✓] Highlights of key commit(s) in Issues, summarizes code contributions: has key commits highlighted 0.8/1
- [✓] Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks: has analytics for work but doesn't go over completely 0.8/1

 Per check.  
 0.55 not attempted/no check 
 0.7 attempted, incomplete, but some runtime
 0.8 mastery and runtime 
 0.9 above and beyond.

 Freeform comment:
 Overall, seems like a great worker and provides a helpful overview of his work in the contributor. One suggestion I have would be that for the binary color segment of his work, maybe if he could include like a place to type in the RGB value as well as a slider, that could be pretty cool, if not maybe he could implement a text variable to show what the actual values of the currently made color is cause I can't currently see what the RGB values are as its just the slider.

Overall grade for Justin Liporada: 0.82/9
(0.9+0.9+0.7+0.8+0.8)/5 = 0.82
