### ISSUE TITLE
Anusha Khobare - Individual Review Ticket

### ISSUE THREAD

**Issue by Flying-Book** [jplip/frontTri2#7]
| Name           | Team+Indi+Teacher | Issues                                     | Key Commit(s)                                         | Analytics            |
|----------------|-------------------|--------------------------------------------|-------------------------------------------------------|----------------------|
| Anusha Khobare |                   | [Team Review Ticket](https://github.com/jplip/frontTri2/issues/4) | SASS buttons, Binary Source, [Binary Shift Interaction Added](https://github.com/jplip/frontTri2/commit/4a329f2a5efe689f9a920152a541475f7805f50f), [Binary Converter + Infographic](https://github.com/jplip/frontTri2/commit/5929e25e833b1723d66fcb7d2f1da48a1368d6a5), [Binary Games](https://github.com/jplip/frontTri2/commit/9d13a6714562951c7abe81e793b095d6313a6241) | See GitHub Profile    |

---
Link to website: https://jplip.github.io/frontTri2/Binary%20Representation/
---
### Project Retrospective: Binary Calculator Development

**What Went Well:**
- **Feature Development:** Successfully implemented the Binary Calculator and Binary Games Functionality.
- **Collaboration:** Demonstrated strong teamwork among the team, individual, and teacher contributions through joint team infographic.
- **Problem-Solving:** Resolved Imaging Issues in Infographic, and Binary Games broken functionality

**What Could Be Improved:**
- **Imaging:** Infographic uses links because image preview was not showing for ASCII Tables
- **Documentation:** Enhance documentation (Read Me + Comments)
- **Issues:** More sub-issues when problems occur + task lists within github

**Key Achievements:**
- Incorporation of SASS buttons and Binary Source, enhancing the project's visual and functional aspects.
- Addition of significant features:
  - [Binary Shift Interaction Added](https://github.com/jplip/frontTri2/commit/4a329f2a5efe689f9a920152a541475f7805f50f)
  - [Binary Converter + Infographic](https://github.com/jplip/frontTri2/commit/5929e25e833b1723d66fcb7d2f1da48a1368d6a5)
  - [Binary Games](https://github.com/jplip/frontTri2/commit/9d13a6714562951c7abe81e793b095d6313a6241)
  ---
Link to Video
https://clipchamp.com/watch/cS7JRP5YDm7
---
Individual Review "My name" grading "Their name"

- [ ] Individual should show that they were key contributor and example to team.  This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom.

Individuals Video, Issue(s), Commits(s)

- [ ] Video in CPT caption style , includes Web demo of key contribution to project, 1 minute
- [ ] Issue(s) that show plans/progress to team objectives
- [ ] Highlights of key commit(s) in Issues, summarizes code contributions
- [ ] Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks

 Per check.  
 0.55 not attempted/no check 
 0.7 attempted, incoomplete, but some runtime
 0.8 mastery and runtime 
 0.9 above and beyond.

 Freeform comment.  
  Provide positivies and growth summary.  
  Justify or comment on final score.  
  Be sure to provide extra details on anything below 0.7 average or above 0.8.

**Comment by Flying-Book** [comment]
Team Review Ticket: https://github.com/jplip/frontTri2/issues/4

**Comment by ArnavNadar** [comment]
Individual Review Arnav grading Anusha

 Individual should show that they were key contributor and example to team. This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom.
Individuals Video, Issue(s), Commits(s)

 Video in CPT caption style , includes Web demo of key contribution to project, 1 minute
 Issue(s) that show plans/progress to team objectives
 Highlights of key commit(s) in Issues, summarizes code contributions
 Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks

Key contributor Score: 1
Good work division
Contributed a lot to their project. 
Talked about team collaboration
Great attitude during presentation
Showed idea making process
Talked about future additions


Video in CPT caption style Score: 0.86
Video went over everything but could have been more specific. 

Issues Score: 0.9
They have their own personal review ticket issue.

Key Commits: 1
Commits are there when I was checking Team Review. There when checking contrbution history. Next time they could maybe corporate it within the exit ticket. 

Git Hub Analytics Score: 0.87
Good amount of commits and each commit has value.
