### ISSUE TITLE
Grading Issue Isabel

### ISSUE THREAD

**Issue by iKAN2025** [jplip/frontTri2#9]
Individual Review "Isabel" grading "Nandan"

- [x] Individual should show that they were key contributor and example to team.  This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom.

Individuals Video, Issue(s), Commits(s)

- [x] Video in CPT caption style , includes Web demo of key contribution to project, 1 minute
- [x] Issue(s) that show plans/progress to team objectives
- [x] Highlights of key commit(s) in Issues, summarizes code contributions
- [x] Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks

 Per check.  
 0.55 not attempted/no check 
 0.7 attempted, incoomplete, but some runtime
 0.8 mastery and runtime 
 0.9 above and beyond.

 Freeform comment.  
  Provide positivies and growth summary.  
  Justify or comment on final score.  
  Be sure to provide extra details on anything below 0.7 average or above 0.8. 

https://jplip.github.io/frontTri2/ Check out Binary Music/Binary Challenge

**Comment by Th35py27** [comment]
Individual Review "Nandan" grading "Isabel"

 - [0.85- contributed with two projects to the team] Individual should show that they were key contributor and example to team. This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom.
Individuals Video, Issue(s), Commits(s)

 - [0.85 - Video was not clear at all, but the demonstration when shown outside was] Video in CPT caption style , includes Web demo of key contribution to project, 1 minute
 - [0.85 - Issues were pretty good and had adequate information ] Issue(s) that show plans/progress to team objectives
 - [0.9 - Pretty good commits and there were multiple] Highlights of key commit(s) in Issues, summarizes code contributions
 - [0.9 - Analytics and commits were pretty consistent for the last few weeks and showed participation likewise] Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks
Per check.
0.55 not attempted/no check
0.7 attempted, incoomplete, but some runtime
0.8 mastery and runtime
0.9 above and beyond.


https://jplip.github.io/frontTri2/ Check out Binary Music/Binary Challenge

Freeform comment.

Project was good overall even though the video was not of good quality. However the binary music was very good and I thought it was very unique (although I haven't really learnt much binary from it).  I did like the idea of getting badges for the logic gate program. The project overall was very good for CPT and had a bunch of information that was related to the project which is a plus point. I wish the binary could've been explained better and this would've helped the project better. Overall, its a pretty good project with information to be taught to people trying to test their knowledge on binary and logic gates. 

Overall grade: 0.88/0.9
